apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app.kubernetes.io/name: exoplanet-summary-api
    app.kubernetes.io/instance: exoplanet-summary-api-1.0.0
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: server
    appName: exoplanet-summary-api
  name: exoplanet-summary-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      appName: exoplanet-summary-api
  template:
    metadata:
      labels:
        appName: exoplanet-summary-api
    spec:
      containers:
      - image: chagen19/exoplanet-summary-api:1.0.0
        imagePullPolicy: IfNotPresent
        name: exoplanet-summary-api
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: "512Mi"
          requests:
            cpu: 250m
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /v1/exoplanetSummary/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /v1/exoplanetSummary/readiness
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: exoplanet-summary-api-1.0.0
    app.kubernetes.io/name: exoplanet-summary-api
    app.kubernetes.io/version: 1.0.0
    appName: exoplanet-summary-api
  name: exoplanet-summary-api
  namespace: default
spec:
  ports:
    - nodePort: 30217
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    appName: exoplanet-summary-api
  type: NodePort
